# Program args
CMD_TOOLS_VERSION = "10406996"
INITIAL_BUILD_TOOL_VERSION = "34.0.0"

# Sdk Manager args
SDK_MAN_ARG_LIST = "--list"
SDK_MAN_ARG_LICENSES = "--licenses"
SDK_MAN_ARG_INSTALL = "--install"
SDK_MAN_ARG_SDK_ROOT = "--sdk_root="
SDK_MAN_ARG_INSTANT_APP = "'extras;google;instantapps'"
SDK_MAN_ARG_WIN_INSTANT_APP = "extras;google;instantapps"
UNIX_SDK_MAN_PATH_END = "/cmdline-tools/bin/sdkmanager"
UNIX_BUILD_TOOLS_PATH_BASE = "/build-tools/"

WIN_SDK_MAN_PATH_END = "\\cmdline-tools\\bin\\sdkmanager.bat"
WIN_BUILD_TOOLS_PATH_BASE = "\\build-tools\\"

ANDROID_HOME = "ANDROID_HOME"
JAVA_HOME = "JAVA_HOME"
PLATFORM_TOOLS = "platform-tools"
EXTRAS_INSTANT_APP = "extras/google/instantapps"
YES_PIPE = "yes |"
UNIX_CHMOD = "chmod +x"
DASH = "-"
SPACE = " "
FORWARD_SLASH = "/"
BACK_SLASH = "\\"
BUILD_TOOLS = "build-tools;"
COMMAND_LINE_TOOLS = "command line tools"
LICENSES_FOlDER = "\\licenses"
WIN_ECHO_Y = "echo y |"
ANDROID_SDK_LICENSE = "android-sdk-license"
ANDROID_SDK_LICENSE_KEY = "24333f8a63b6825ea9c5514f83c2829b004d1fee"
ANDROID_SDK_PREVIEW_LICENSE = "android-sdk-preview-license"
ANDROID_SDK_PREVIEW_LICENSE_KEY = "84831b9409646a918e30573bab4c9c91346d8abd"

LATEST_ZIP = "_latest.zip"
CMD_LINE_URL_BASE = "https://dl.google.com/android/repository/commandlinetools-"

WINDOWS = "windows"
WIN = "win"
DARWIN = "darwin"
MAC = "mac"
LINUX = "linux"
